namespace Migrator
{
    /// <summary>
    /// Definisi semua migrasi (forward-only), urut berdasarkan prefix Id.
    /// DDL dibungkus PL/SQL yang menelan error "objek sudah ada" sehingga
    /// migrasi aman dijalankan ulang meski DDL Oracle auto-commit.
    /// </summary>
    public static class Migrations
    {
        // ORA-00955 name already used, -01408 column already indexed,
        // -02260 table can have only one PK, -02275 such a referential constraint already exists.
        private static string Ddl(string ddl) =>
            "BEGIN\n" +
            "   EXECUTE IMMEDIATE '" + ddl.Replace("'", "''").Trim() + "';\n" +
            "EXCEPTION WHEN OTHERS THEN\n" +
            "   IF SQLCODE NOT IN (-955, -1408, -2260, -2275) THEN RAISE; END IF;\n" +
            "END;";

        // Insert idempotent berdasarkan keberadaan baris.
        private static string SeedApp(string id, string name) =>
            $"INSERT INTO POS_APP (APP_ID, APP_NAME, IS_ACTIVE) " +
            $"SELECT '{id}', '{name}', 1 FROM DUAL " +
            $"WHERE NOT EXISTS (SELECT 1 FROM POS_APP WHERE APP_ID = '{id}')";

        private static string SeedRole(string name) =>
            $"INSERT INTO POS_ROLE (ROLE_NAME) " +
            $"SELECT '{name}' FROM DUAL " +
            $"WHERE NOT EXISTS (SELECT 1 FROM POS_ROLE WHERE ROLE_NAME = '{name}')";

        public static readonly Migration[] All =
        {
            new Migration(
                "0001_create_login_schema",
                "Tabel login & RBAC (POS_APP/POS_ROLE/POS_USER/POS_USER_ACCESS) + seed app/role",
                new[]
                {
                    Ddl(@"CREATE TABLE POS_APP (
  APP_ID    VARCHAR2(20)  CONSTRAINT PK_POS_APP PRIMARY KEY,
  APP_NAME  VARCHAR2(100) NOT NULL,
  IS_ACTIVE NUMBER(1)     DEFAULT 1 NOT NULL CONSTRAINT CK_POS_APP_ACTIVE CHECK (IS_ACTIVE IN (0,1)))"),

                    Ddl(@"CREATE TABLE POS_ROLE (
  ROLE_ID   NUMBER       GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_POS_ROLE PRIMARY KEY,
  ROLE_NAME VARCHAR2(50) NOT NULL CONSTRAINT UQ_POS_ROLE_NAME UNIQUE,
  IS_ACTIVE NUMBER(1)    DEFAULT 1 NOT NULL CONSTRAINT CK_POS_ROLE_ACTIVE CHECK (IS_ACTIVE IN (0,1)))"),

                    Ddl(@"CREATE TABLE POS_USER (
  USER_ID         NUMBER        GENERATED BY DEFAULT AS IDENTITY CONSTRAINT PK_POS_USER PRIMARY KEY,
  USERNAME        VARCHAR2(25)  NOT NULL CONSTRAINT UQ_POS_USER_NAME UNIQUE,
  FULL_NAME       VARCHAR2(100),
  PASSWORD_HASH   VARCHAR2(200) NOT NULL,
  IS_ACTIVE       NUMBER(1)     DEFAULT 1 NOT NULL CONSTRAINT CK_POS_USER_ACTIVE CHECK (IS_ACTIVE IN (0,1)),
  IS_LOCKED       NUMBER(1)     DEFAULT 0 NOT NULL CONSTRAINT CK_POS_USER_LOCKED CHECK (IS_LOCKED IN (0,1)),
  FAILED_ATTEMPTS NUMBER        DEFAULT 0 NOT NULL,
  CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL)"),

                    Ddl(@"CREATE TABLE POS_USER_ACCESS (
  USER_ID   NUMBER       NOT NULL,
  APP_ID    VARCHAR2(20) NOT NULL,
  ROLE_ID   NUMBER       NOT NULL,
  IS_ACTIVE NUMBER(1)    DEFAULT 1 NOT NULL CONSTRAINT CK_POS_ACCESS_ACTIVE CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT PK_POS_USER_ACCESS PRIMARY KEY (USER_ID, APP_ID),
  CONSTRAINT FK_ACCESS_USER FOREIGN KEY (USER_ID) REFERENCES POS_USER(USER_ID),
  CONSTRAINT FK_ACCESS_APP  FOREIGN KEY (APP_ID)  REFERENCES POS_APP(APP_ID),
  CONSTRAINT FK_ACCESS_ROLE FOREIGN KEY (ROLE_ID) REFERENCES POS_ROLE(ROLE_ID))"),

                    Ddl("CREATE INDEX IX_POS_USER_ACCESS_APP ON POS_USER_ACCESS (APP_ID)"),

                    SeedApp("PENJUALAN",  "Aplikasi Penjualan (Kasir)"),
                    SeedApp("BACKOFFICE", "Aplikasi BackOffice"),
                    SeedApp("PEMBELIAN",  "Modul Pembelian"),

                    SeedRole("ADMIN"),
                    SeedRole("MANAGER"),
                    SeedRole("KABAG"),
                    SeedRole("KASIR"),
                    SeedRole("STAFF"),
                }),
        };
    }
}
