--------------------------------------------------------------------------------
-- POS Login / RBAC schema
-- Aplikasi: PENJUALAN, BACKOFFICE, PEMBELIAN (Pembelian = APPID terpisah)
-- Target  : Oracle (skema KOPKAR)
--
-- Catatan:
--   * Hashing password = PBKDF2/SHA256, 600000 iter, salt 16B, key 32B.
--     Disimpan self-describing: PBKDF2-SHA256$<iter>$<saltB64>$<hashB64>.
--     Buat hash via layar Manajemen User atau db/generate_admin_hash.ps1.
--   * Username selalu disimpan lowercase (login meng-ToLower input).
--   * Jalankan sekali, lalu seed user admin (lihat bagian SEED ADMIN).
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- 1. TABEL
--------------------------------------------------------------------------------

-- Katalog aplikasi
CREATE TABLE POS_APP (
  APP_ID    VARCHAR2(20)  CONSTRAINT PK_POS_APP PRIMARY KEY,  -- PENJUALAN | BACKOFFICE | PEMBELIAN
  APP_NAME  VARCHAR2(100) NOT NULL,
  IS_ACTIVE NUMBER(1)     DEFAULT 1 NOT NULL
                          CONSTRAINT CK_POS_APP_ACTIVE CHECK (IS_ACTIVE IN (0,1))
);

-- Katalog role
CREATE TABLE POS_ROLE (
  ROLE_ID   NUMBER        GENERATED BY DEFAULT AS IDENTITY
                          CONSTRAINT PK_POS_ROLE PRIMARY KEY,
  ROLE_NAME VARCHAR2(50)  NOT NULL CONSTRAINT UQ_POS_ROLE_NAME UNIQUE,
  IS_ACTIVE NUMBER(1)     DEFAULT 1 NOT NULL
                          CONSTRAINT CK_POS_ROLE_ACTIVE CHECK (IS_ACTIVE IN (0,1))
);

-- Akun user (satu identitas untuk semua app)
CREATE TABLE POS_USER (
  USER_ID         NUMBER        GENERATED BY DEFAULT AS IDENTITY
                                CONSTRAINT PK_POS_USER PRIMARY KEY,
  USERNAME        VARCHAR2(25)  NOT NULL CONSTRAINT UQ_POS_USER_NAME UNIQUE,
  FULL_NAME       VARCHAR2(100),
  PASSWORD_HASH   VARCHAR2(200) NOT NULL,
  IS_ACTIVE       NUMBER(1)     DEFAULT 1 NOT NULL
                                CONSTRAINT CK_POS_USER_ACTIVE CHECK (IS_ACTIVE IN (0,1)),
  IS_LOCKED       NUMBER(1)     DEFAULT 0 NOT NULL
                                CONSTRAINT CK_POS_USER_LOCKED CHECK (IS_LOCKED IN (0,1)),
  FAILED_ATTEMPTS NUMBER        DEFAULT 0 NOT NULL,
  CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);

-- Akses: user x app x role (satu user bisa akses banyak app; tiap app punya satu role)
CREATE TABLE POS_USER_ACCESS (
  USER_ID   NUMBER       NOT NULL,
  APP_ID    VARCHAR2(20) NOT NULL,
  ROLE_ID   NUMBER       NOT NULL,
  IS_ACTIVE NUMBER(1)    DEFAULT 1 NOT NULL
                         CONSTRAINT CK_POS_ACCESS_ACTIVE CHECK (IS_ACTIVE IN (0,1)),
  CONSTRAINT PK_POS_USER_ACCESS PRIMARY KEY (USER_ID, APP_ID),
  CONSTRAINT FK_ACCESS_USER FOREIGN KEY (USER_ID) REFERENCES POS_USER(USER_ID),
  CONSTRAINT FK_ACCESS_APP  FOREIGN KEY (APP_ID)  REFERENCES POS_APP(APP_ID),
  CONSTRAINT FK_ACCESS_ROLE FOREIGN KEY (ROLE_ID) REFERENCES POS_ROLE(ROLE_ID)
);

CREATE INDEX IX_POS_USER_ACCESS_APP ON POS_USER_ACCESS (APP_ID);

--------------------------------------------------------------------------------
-- 2. SEED
--------------------------------------------------------------------------------

INSERT INTO POS_APP (APP_ID, APP_NAME, IS_ACTIVE) VALUES ('PENJUALAN',  'Aplikasi Penjualan (Kasir)', 1);
INSERT INTO POS_APP (APP_ID, APP_NAME, IS_ACTIVE) VALUES ('BACKOFFICE', 'Aplikasi BackOffice',        1);
INSERT INTO POS_APP (APP_ID, APP_NAME, IS_ACTIVE) VALUES ('PEMBELIAN',  'Modul Pembelian',            1);

INSERT INTO POS_ROLE (ROLE_NAME) VALUES ('ADMIN');
INSERT INTO POS_ROLE (ROLE_NAME) VALUES ('MANAGER');
INSERT INTO POS_ROLE (ROLE_NAME) VALUES ('KABAG');
INSERT INTO POS_ROLE (ROLE_NAME) VALUES ('KASIR');
INSERT INTO POS_ROLE (ROLE_NAME) VALUES ('STAFF');

COMMIT;

--------------------------------------------------------------------------------
-- 3. SEED USER ADMIN
--    PASSWORD_HASH wajib dibuat lewat aplikasi (layar Manajemen User) atau
--    db/generate_admin_hash.ps1 -- script tsb mencetak INSERT lengkap.
--    Placeholder di bawah HARUS diganti dengan hash valid sebelum dipakai.
--------------------------------------------------------------------------------
-- INSERT INTO POS_USER (USERNAME, FULL_NAME, PASSWORD_HASH)
--   VALUES ('admin', 'Administrator', 'PBKDF2-SHA256$600000$<<saltB64>>$<<hashB64>>');
-- INSERT INTO POS_USER_ACCESS (USER_ID, APP_ID, ROLE_ID)
--   SELECT u.USER_ID, a.APP_ID, r.ROLE_ID
--   FROM POS_USER u CROSS JOIN POS_APP a JOIN POS_ROLE r ON r.ROLE_NAME='ADMIN'
--   WHERE u.USERNAME='admin';
-- COMMIT;
